// export const GET_FAQS = "GET_FAQS"

export const GET_FAQS = "GET_FAQS"
export const  GET_FAQS_SUCCESS = " GET_FAQS_SUCCESS"
export const GET_FAQS_FAIL = "GET_FAQS_FAIL"

export const GET_FAQS_COUNT_SUCCESS = "GET_FAQS_COUNT_SUCCESS"
export const GET_FAQS_COUNT_FAIL =  "GET_FAQS_COUNT_FAIL"