export const EDIT_EDUCATION_DETAIL = "EDIT_EDUCATION_DETAIL"
export const EDIT_EDUCATION_DETAIL_SUCCESS = "EDIT_EDUCATION_DETAIL_SUCCESS"
export const EDIT_EDUCATION_DETAIL_FAIL = "EDIT_EDUCATION_DETAIL_FAIL"
