FROM node:14-alpine AS development
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install --no-optional
COPY . .
COPY .env.development .env.production
RUN [ "npm", "run", "build" ]


FROM nginx:stable-alpine
COPY --from=development /app/build/ /usr/share/nginx/html
COPY ./default.conf /etc/nginx/conf.d