export const GET_BATCHES = "GET_BATCHES"
export const GET_BATCHES_SUCCESS = "GET_BATCHES_SUCCESS"
export const GET_BATCHES_FAIL = "GET_BATCHES_FAIL"

export const GET_BATCHES_COUNT_SUCCESS = "GET_BATCHES_COUNT_SUCCESS"
export const GET_BATCHES_COUNT_FAIL = "GET_BATCHES_COUNT_FAIL"

export const DELETE_LEARNER = "DELETE_LEARNER"
export const DELETE_LEARNER_SUCCESS = "DELETE_LEARNER_SUCCESS"
export const DELETE_LEARNER_FAIL = "DELETE_LEARNER_FAIL"

export const FILTER_STATUS_LEARNER = "FILTER_STATUS_LEARNER"
