export const GET_COURSE_INFORMATION = "GET_COURSE_INFORMATION"
export const GET_COURSE_INFORMATION_SUCCESS = "GET_COURSE_INFORMATION_SUCCESS"
export const GET_COURSE_INFORMATION_FAIL = "GET_COURSE_INFORMATION_FAIL"

export const EDIT_COURSE_INFORMATION = "EDIT_COURSE_INFORMATION"
export const EDIT_COURSE_INFORMATION_SUCCESS = "EDIT_COURSE_INFORMATION_SUCCESS"
export const EDIT_COURSE_INFORMATION_FAIL = "EDIT_COURSE_INFORMATION_FAIL"

export const EDIT_CARD_CONFIGURATION = "EDIT_CARD_CONFIGURATION"
export const EDIT_CARD_CONFIGURATION_SUCCESS = "EDIT_CARD_CONFIGURATION_SUCCESS"
export const EDIT_CARD_CONFIGURATION_FAIL = "EDIT_CARD_CONFIGURATION_FAIL"
