export const GET_APPLICATION_LISTING = "GET_APPLICATION_LISTING";
export const GET_APPLICATION_LISTING_SUCCESS =
  "GET_APPLICATION_LISTING_SUCCESS";
export const GET_APPLICATION_LISTING_FAIL = "GET_APPLICATION_LISTING_FAIL";

export const GET_APPLICATION_LISTING_COUNT_SUCCESS =
  "GET_APPLICATION_LISTING_COUNT_SUCCESS";
export const GET_APPLICATION_LISTING_COUNT_FAIL =
  "GET_APPLICATION_LISTING_COUNT_FAIL";
